// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wvhpwclgevtdzrfqtvvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aHB3Y2xnZXZ0ZHpyZnF0dnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzg0NjQsImV4cCI6MjA2NTUxNDQ2NH0.Ah29EWz61Vg2o-ku27R4L4G6TR5sSNLeNQCdG0vnalk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);